-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS exercise.answers DROP CONSTRAINT IF EXISTS choice_answer_fk;

ALTER TABLE IF EXISTS exercise.answers DROP CONSTRAINT IF EXISTS submission_answer_fk;

ALTER TABLE IF EXISTS exercise.choices DROP CONSTRAINT IF EXISTS question_choice_fk;

ALTER TABLE IF EXISTS exercise.questions DROP CONSTRAINT IF EXISTS exercise_question_fk;

ALTER TABLE IF EXISTS exercise.scores DROP CONSTRAINT IF EXISTS submission_score_fk;

ALTER TABLE IF EXISTS exercise.submissions DROP CONSTRAINT IF EXISTS exercise_submission_fk;



DROP TABLE IF EXISTS exercise.answers;

CREATE TABLE IF NOT EXISTS exercise.answers
(
    id text COLLATE pg_catalog."default" NOT NULL,
    submission_id text COLLATE pg_catalog."default" NOT NULL,
    choice_id text COLLATE pg_catalog."default",
    is_marked boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT answer_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS exercise.choices;

CREATE TABLE IF NOT EXISTS exercise.choices
(
    id text COLLATE pg_catalog."default" NOT NULL,
    question_id text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    point text COLLATE pg_catalog."default" NOT NULL,
    is_correct boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT choice_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS exercise.exercises;

CREATE TABLE IF NOT EXISTS exercise.exercises
(
    id text COLLATE pg_catalog."default" NOT NULL,
    test_type_id text COLLATE pg_catalog."default" NOT NULL,
    title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    "time" integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exercise_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS exercise.questions;

CREATE TABLE IF NOT EXISTS exercise.questions
(
    id text COLLATE pg_catalog."default" NOT NULL,
    exercise_id text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    image text COLLATE pg_catalog."default",
    point integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS exercise.scores;

CREATE TABLE IF NOT EXISTS exercise.scores
(
    id text COLLATE pg_catalog."default" NOT NULL,
    submission_id text COLLATE pg_catalog."default" NOT NULL,
    score integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT score_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS exercise.submissions;

CREATE TABLE IF NOT EXISTS exercise.submissions
(
    id text COLLATE pg_catalog."default" NOT NULL,
    user_id text COLLATE pg_catalog."default" NOT NULL,
    exercise_id text COLLATE pg_catalog."default" NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone NOT NULL,
    time_required time without time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT submission_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS exercise.answers
    ADD CONSTRAINT choice_answer_fk FOREIGN KEY (choice_id)
    REFERENCES exercise.choices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exercise.answers
    ADD CONSTRAINT submission_answer_fk FOREIGN KEY (submission_id)
    REFERENCES exercise.submissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exercise.choices
    ADD CONSTRAINT question_choice_fk FOREIGN KEY (question_id)
    REFERENCES exercise.questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exercise.questions
    ADD CONSTRAINT exercise_question_fk FOREIGN KEY (exercise_id)
    REFERENCES exercise.exercises (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exercise.scores
    ADD CONSTRAINT submission_score_fk FOREIGN KEY (submission_id)
    REFERENCES exercise.submissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exercise.submissions
    ADD CONSTRAINT exercise_submission_fk FOREIGN KEY (exercise_id)
    REFERENCES exercise.exercises (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;