-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS quiz.answers DROP CONSTRAINT IF EXISTS choice_answer_fk;

ALTER TABLE IF EXISTS quiz.answers DROP CONSTRAINT IF EXISTS submission_answer_fk;

ALTER TABLE IF EXISTS quiz.choices DROP CONSTRAINT IF EXISTS question_choice_fk;

ALTER TABLE IF EXISTS quiz.questions DROP CONSTRAINT IF EXISTS quiz_question_fk;

ALTER TABLE IF EXISTS quiz.scores DROP CONSTRAINT IF EXISTS submission_score_fk;

ALTER TABLE IF EXISTS quiz.submissions DROP CONSTRAINT IF EXISTS quiz_submission_fk;



DROP TABLE IF EXISTS quiz.answers;

CREATE TABLE IF NOT EXISTS quiz.answers
(
    id text COLLATE pg_catalog."default" NOT NULL,
    submission_id text COLLATE pg_catalog."default" NOT NULL,
    choice_id text COLLATE pg_catalog."default",
    is_marked boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT answer_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS quiz.choices;

CREATE TABLE IF NOT EXISTS quiz.choices
(
    id text COLLATE pg_catalog."default" NOT NULL,
    question_id text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    point integer NOT NULL,
    is_correct boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT choices_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS quiz.questions;

CREATE TABLE IF NOT EXISTS quiz.questions
(
    id text COLLATE pg_catalog."default" NOT NULL,
    quiz_id text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    image text COLLATE pg_catalog."default",
    point integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS quiz.quizzes;

CREATE TABLE IF NOT EXISTS quiz.quizzes
(
    id text COLLATE pg_catalog."default" NOT NULL,
    sub_subject_id text COLLATE pg_catalog."default" NOT NULL,
    test_type_id text COLLATE pg_catalog."default" NOT NULL,
    open timestamp with time zone NOT NULL,
    title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    "time" integer NOT NULL,
    point integer NOT NULL,
    attempt integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT quiz_pkey PRIMARY KEY (id),
    CONSTRAINT quiz_uq UNIQUE (title)
);

DROP TABLE IF EXISTS quiz.scores;

CREATE TABLE IF NOT EXISTS quiz.scores
(
    id text COLLATE pg_catalog."default" NOT NULL,
    submission_id text COLLATE pg_catalog."default" NOT NULL,
    score integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT score_pket PRIMARY KEY (id)
);

DROP TABLE IF EXISTS quiz.submissions;

CREATE TABLE IF NOT EXISTS quiz.submissions
(
    id text COLLATE pg_catalog."default" NOT NULL,
    user_id text COLLATE pg_catalog."default" NOT NULL,
    quiz_id text COLLATE pg_catalog."default" NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_required time without time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT submission_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS quiz.answers
    ADD CONSTRAINT choice_answer_fk FOREIGN KEY (choice_id)
    REFERENCES quiz.choices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS quiz.answers
    ADD CONSTRAINT submission_answer_fk FOREIGN KEY (submission_id)
    REFERENCES quiz.submissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS quiz.choices
    ADD CONSTRAINT question_choice_fk FOREIGN KEY (question_id)
    REFERENCES quiz.questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS quiz.questions
    ADD CONSTRAINT quiz_question_fk FOREIGN KEY (quiz_id)
    REFERENCES quiz.quizzes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS quiz.scores
    ADD CONSTRAINT submission_score_fk FOREIGN KEY (submission_id)
    REFERENCES quiz.submissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS quiz.submissions
    ADD CONSTRAINT quiz_submission_fk FOREIGN KEY (quiz_id)
    REFERENCES quiz.quizzes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;